MsgBox"error"
MsgBox"error"
MsgBox"Presiona aceptar para borrar un archivo importante de Windows"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"Archivo eliminado"
MsgBox"DEBE REINSTALAR WINDOWS"